version: '3.1'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "9000:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise


  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - odoo-pgadmin-data:/var/lib/pgadmin
    ports:
      - "8045:45"
    links:
      - "db:pgsql-server"
    environment:
      PGADMIN_DEFAULT_EMAIL: fredditampubolon04@gmail.com
      PGADMIN_DEFAULT_PASSWORD: BlokJ1No22!@#
      PGADMIN_LISTEN_PORT: 45
    depends_on:
      - db

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-pgadmin-data: